from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

from .tools import changed_files, git_diff, read_project_file, search_project_files, write_project_file


def _render_find_usage(query: str, roots: list[str]) -> str:
    hits = search_project_files(query=query, roots=roots)
    grouped: dict[str, list[dict]] = defaultdict(list)
    for hit in hits:
        grouped[hit["path"]].append(hit)
    by_root: dict[str, int] = defaultdict(int)
    for path in grouped:
        top = path.split("/", 2)[:2]
        root_hint = "/".join(top) if len(top) == 2 else path
        by_root[root_hint] += len(grouped[path])

    lines: list[str] = []
    lines.append(f"# Find Usage Report: `{query}`")
    lines.append("")
    lines.append(f"- Search roots: {', '.join(f'`{r}`' for r in roots)}")
    lines.append(f"- Matched files: **{len(grouped)}**")
    lines.append(f"- Total matches: **{len(hits)}**")
    lines.append("")

    lines.append("## Match Hierarchy")
    for root_hint in sorted(by_root.keys()):
        lines.append(f"- `{root_hint}`: {by_root[root_hint]} matches")
    if not by_root:
        lines.append("- no hierarchy matches")
    lines.append("")

    lines.append("## Matched Files")
    for path in sorted(grouped.keys()):
        lines.append(f"- `{path}` ({len(grouped[path])} matches)")
    if not grouped:
        lines.append("- no matches")
    lines.append("")

    lines.append("## Snippets")
    for path in sorted(grouped.keys()):
        lines.append(f"### `{path}`")
        for hit in grouped[path][:8]:
            lines.append(f"- L{hit['line']}: `{hit['snippet']}`")
        lines.append("")

    lines.append("## Analysis")
    if grouped:
        lines.append("- The symbol appears across configuration/docs codepaths, not a single file.")
        lines.append("- Changes should stay synchronized between config defaults, env examples, and README docs.")
        lines.append("- This query is safe to validate with repository-wide search before edits.")
    else:
        lines.append("- No usage found under `ai_assistant/`; likely typo or removed symbol.")
    lines.append("")

    lines.append("## Related Invariants / Risks")
    if query == "RAG_INCLUDE":
        lines.append("- `ai_assistant/support/data/faq.md` should stay included in RAG sources.")
        lines.append("- `.cursor/docs` must not be indexed.")
        lines.append("- Auto-generated AWS API paths should not be broadly indexed.")
    else:
        lines.append("- Keep docs and examples aligned with real behavior.")
        lines.append("- Prefer scoped edits and re-run local validation commands.")

    return "\n".join(lines).strip() + "\n"


def cmd_find_usage(args: argparse.Namespace) -> int:
    roots = args.root or ["ai_assistant"]
    report = _render_find_usage(args.query, roots)
    print(report)
    return 0


def _classify_file(path: str) -> str:
    if path.startswith("ai_assistant/file_ops/"):
        return "Day 34 file operations assistant"
    if path.startswith("ai_assistant/support/"):
        return "Day 33 support assistant"
    if path == "ai_assistant/README.md":
        return "Documentation"
    if path in {"ai_assistant/config.py", "ai_assistant/.env.example"}:
        return "Configuration"
    return "Other"


def _build_changelog(changed: list[str]) -> str:
    by_area: dict[str, list[str]] = defaultdict(list)
    for path in changed:
        by_area[_classify_file(path)].append(path)

    lines: list[str] = []
    lines.append("# Changelog")
    lines.append("")
    lines.append("## Summary")
    if not changed:
        lines.append("- No changes detected under `ai_assistant/`.")
    else:
        for area in sorted(by_area.keys()):
            lines.append(f"- **{area}:** {len(by_area[area])} file(s)")
    lines.append("")

    lines.append("## Changed Files")
    if not changed:
        lines.append("- none")
    else:
        for path in changed:
            lines.append(f"- `{path}`")
    lines.append("")

    lines.append("## Notes")
    lines.append("- Generated by `python -m ai_assistant.file_ops.assistant changelog`.")
    lines.append("- Reproducible from current git working tree state.")
    lines.append("")

    return "\n".join(lines)


def cmd_changelog(args: argparse.Namespace) -> int:
    files = changed_files()
    # Trigger git diff collection to ensure command output remains reproducible and tied to current state.
    _ = git_diff(paths=files if files else None)
    body = _build_changelog(files)
    write_project_file(args.output, body)
    print(f"wrote changelog: {args.output}")
    print(f"files considered: {len(files)}")
    return 0


def _check_rule(name: str, ok: bool, detail: str) -> tuple[bool, str]:
    status = "PASS" if ok else "FAIL"
    return ok, f"- [{status}] {name}: {detail}"


def cmd_rules_check(_: argparse.Namespace) -> int:
    config_text = read_project_file("ai_assistant/config.py")
    env_example = read_project_file("ai_assistant/.env.example")
    readme = read_project_file("ai_assistant/README.md")

    checks = []
    checks.append(
        _check_rule(
            ".cursor/docs excluded from rag include",
            ".cursor/docs" not in config_text and ".cursor/docs" not in env_example,
            "must not be indexed",
        )
    )
    checks.append(
        _check_rule(
            "aws/api excluded from rag include",
            "localstack-core/localstack/aws/api" not in config_text
            and "localstack-core/localstack/aws/api" not in env_example,
            "auto-generated API files should stay out",
        )
    )
    checks.append(
        _check_rule(
            "support faq included in rag include",
            "ai_assistant/support/data/faq.md" in config_text
            and "ai_assistant/support/data/faq.md" in env_example,
            "faq should be part of indexed docs",
        )
    )
    checks.append(
        _check_rule(
            "readme mentions day 33 support assistant",
            "Day 33 — User Support Assistant" in readme and "support/" in readme,
            "support docs should exist",
        )
    )

    file_ops_dir = Path("ai_assistant/file_ops")
    checks.append(
        _check_rule(
            "file ops module exists under ai_assistant/file_ops",
            file_ops_dir.exists()
            and (file_ops_dir / "assistant.py").exists()
            and (file_ops_dir / "tools.py").exists(),
            "expected module files should exist",
        )
    )

    print("# Rules Check")
    print("")
    all_ok = True
    for ok, line in checks:
        all_ok = all_ok and ok
        print(line)

    print("")
    print(f"overall: {'PASS' if all_ok else 'FAIL'}")
    return 0 if all_ok else 1


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ai_assistant.file_ops.assistant")
    sub = parser.add_subparsers(dest="command", required=True)

    p_find = sub.add_parser("find-usage", help="search and analyze symbol usage")
    p_find.add_argument("query", help="text to search for")
    p_find.add_argument(
        "--root",
        action="append",
        default=[],
        help="search root under ai_assistant/ (repeatable)",
    )
    p_find.set_defaults(func=cmd_find_usage)

    p_changelog = sub.add_parser("changelog", help="generate changelog from current changes")
    p_changelog.add_argument(
        "--output",
        default="ai_assistant/CHANGELOG.md",
        help="output file path under ai_assistant/",
    )
    p_changelog.set_defaults(func=cmd_changelog)

    p_rules = sub.add_parser("rules-check", help="validate project invariants")
    p_rules.set_defaults(func=cmd_rules_check)

    return parser


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = _build_parser()
    args = parser.parse_args()
    raise SystemExit(args.func(args))


if __name__ == "__main__":
    main()

